import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author USER
 */
public class KonversiSuhu extends javax.swing.JFrame {

    /**
     * Creates new form KonversiSuhu
     */
    public KonversiSuhu() {
        initComponents();
    }
public double konversiSuhu(double suhu, String SkalaAsal, String SkalaTujuan) {
    if (SkalaAsal.equals("Celsius") && SkalaTujuan.equals("Fahrenheit")) {
        return (suhu * 9/5) + 32;
    } else if (SkalaAsal.equals("Celsius") && SkalaTujuan.equals("Kelvin")) {
        return suhu + 273.15;
    } else if (SkalaAsal.equals("Celsius") && SkalaTujuan.equals("Reamur")) {
        return suhu * 4/5;
    } else if (SkalaAsal.equals("Fahrenheit") && SkalaTujuan.equals("Celsius")) {
        return (suhu - 32) * 5/9;
    } else if (SkalaAsal.equals("Fahrenheit") && SkalaTujuan.equals("Kelvin")) {
        return (suhu - 32) * 5/9 + 273.15;
    } else if (SkalaAsal.equals("Fahrenheit") && SkalaTujuan.equals("Reamur")) {
        return (suhu - 32) * 4/9;
    } else if (SkalaAsal.equals("Kelvin") && SkalaTujuan.equals("Celsius")) {
        return suhu - 273.15;
    } else if (SkalaAsal.equals("Kelvin") && SkalaTujuan.equals("Fahrenheit")) {
        return (suhu - 273.15) * 9/5 + 32;
    } else if (SkalaAsal.equals("Kelvin") && SkalaTujuan.equals("Reamur")) {
        return (suhu - 273.15) * 4/5;
    } else if (SkalaAsal.equals("Reamur") && SkalaTujuan.equals("Celsius")) {
        return suhu * 5/4;
    } else if (SkalaAsal.equals("Reamur") && SkalaTujuan.equals("Fahrenheit")) {
        return (suhu * 9/4) + 32;
    } else if (SkalaAsal.equals("Reamur") && SkalaTujuan.equals("Kelvin")) {
        return (suhu * 5/4) + 273.15;
    }
    return suhu; // jika skala asal dan tujuan sama
}



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        InputSuhu = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        SkalaAsal = new javax.swing.JComboBox<>();
        SkalaTujuan = new javax.swing.JComboBox<>();
        Ksuhu = new javax.swing.JButton();
        Hasil = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Suhu");

        InputSuhu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                InputSuhuKeyTyped(evt);
            }
        });

        jLabel2.setText("Skala Asal");

        jLabel3.setText("Skala Tujuan");

        SkalaAsal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Celsius", "Fahrenheit", "Reamur", "Kelvin" }));

        SkalaTujuan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Celsius", "Fahrenheit", "Reamur", "Kelvin" }));

        Ksuhu.setText("Konversi");
        Ksuhu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KsuhuActionPerformed(evt);
            }
        });

        Hasil.setText("Hasil Konversi");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addGap(18, 18, 18)
                            .addComponent(SkalaTujuan, 0, 90, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addComponent(jLabel2))
                            .addGap(33, 33, 33)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(InputSuhu)
                                .addComponent(SkalaAsal, 0, 91, Short.MAX_VALUE))))
                    .addComponent(Ksuhu)
                    .addComponent(Hasil))
                .addContainerGap(205, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(InputSuhu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(SkalaAsal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(SkalaTujuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(Ksuhu)
                .addGap(18, 18, 18)
                .addComponent(Hasil)
                .addContainerGap(108, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void KsuhuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KsuhuActionPerformed
            try {
        double suhu = Double.parseDouble(InputSuhu.getText());
        String skalaAsal = SkalaAsal.getSelectedItem().toString();
        String skalaTujuan = SkalaTujuan.getSelectedItem().toString();
        
        double hasil = konversiSuhu(suhu, skalaAsal, skalaTujuan);
        Hasil.setText(String.format("%.2f", hasil)); // Menampilkan hasil pada JLabel
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Input tidak valid. Masukkan angka saja.", "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_KsuhuActionPerformed

    private void InputSuhuKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_InputSuhuKeyTyped
        char c = evt.getKeyChar();
if (!Character.isDigit(c)) {
    evt.consume();
}
    }//GEN-LAST:event_InputSuhuKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KonversiSuhu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KonversiSuhu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KonversiSuhu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KonversiSuhu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KonversiSuhu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Hasil;
    private javax.swing.JTextField InputSuhu;
    private javax.swing.JButton Ksuhu;
    private javax.swing.JComboBox<String> SkalaAsal;
    private javax.swing.JComboBox<String> SkalaTujuan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables

    private double konversiSuhu(JTextField InputSuhu, JComboBox<String> SkalaAsal, JComboBox<String> SkalaTujuan) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
